import { getSession, signIn } from 'next-auth/react';
import Head from 'next/head';
import { GetServerSideProps } from 'next/types';
import { MouseEvent, useCallback } from 'react';


export const getServerSideProps: GetServerSideProps = async({ req }) => {
  const session = await getSession({ req })

  if(session){
    return {
      redirect: {
        destination: '/dashboard',
        permanent: false
      }
    }
  }
  
  return {
    props: {}
  }
  
} 


export default function Home() {

  const handleSignIn = useCallback((e: MouseEvent<HTMLButtonElement>) => {
    e.preventDefault()
    signIn('github')
  }, [])

  return (
    <>
      <Head>
        <title>SignIn | Hermes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <button onClick={handleSignIn}>SignIn</button>
      </main>
    </>
  )
}
