import { getSession, signIn } from 'next-auth/react';
import Head from 'next/head';
import { GetServerSideProps } from 'next/types';
import { MouseEvent, useCallback } from 'react';


export const getServerSideProps: GetServerSideProps = async(ctx) => {
  
  const session = await getSession(ctx)

  console.log(session?.user);

  if(!session){
    return {
      props: {}
    }
  }
  
  return {
    redirect: {
      destination: '/dashboard',
      permanent: false,
      basePath: process.env.NEXTAUTH_URL
    },
  }
  
} 


export default function Home() {

  const handleSignIn = useCallback((e: MouseEvent<HTMLButtonElement>) => {
    e.preventDefault()
    signIn('github')
  }, [])

  return (
    <>
      <Head>
        <title>SignIn | Hermes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <button onClick={handleSignIn}>SignIn</button>
      </main>
    </>
  )
}
